apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  labels:
    app: capstone-app
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
        
    spec:
      containers:
      - name: capstone-website
        image: ahmedhosny333/capstone-project
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-lb
  labels:
    app: capstone-app
    
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer